### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by raineorshine** [algal/cocoa-sniff#2]
Looks like what I need to try to guess the encoding of a file that was "Saved for Web" from Mac Word.

Is the binary available somewhere, or do I have to compile from source?

**Comment by algal** [comment]
I just pushed a new commit with a compiled binary. I can't guarantee it will work with your architecture, but it might.

**Comment by raineorshine** [comment]
Thanks for the response! I know it’s been a while ;). I’ll try it.
